-- =========================================================
-- MWM Agency OS — Migration 042: Fix over-aggressive notification blocker
-- Run this in Supabase SQL Editor AFTER migration_041
-- =========================================================
-- migration_041 added a BEFORE INSERT trigger on notifications that
-- dropped any row where new.user_id = auth.uid(). The intent was "don't
-- notify someone about their own action" -- but it was checking the
-- wrong thing.
--
-- Inside a SECURITY DEFINER trigger, auth.uid() is still the person
-- who performed the action. So when Staff A changes a task's status,
-- EVERY notification generated by that action runs with
-- auth.uid() = Staff A -- including the rows addressed to the client
-- and other assignees. The blocker only compares the recipient
-- (new.user_id) against auth.uid(), which is correct for the sender's
-- own row, but it was firing during inserts for everyone else too...
--
-- ...which is fine, actually: user_id differs for those, so they pass.
-- The real problem is subtler: several notification functions insert
-- via `insert ... select` over multiple recipients, and a BEFORE
-- INSERT trigger returning NULL in that context silently drops rows
-- without error, making failures invisible and hard to reason about.
-- Combined with migration_038 already excluding the actor correctly in
-- every function, this trigger is redundant belt-and-braces that costs
-- more than it protects.
--
-- Removing it, and instead fixing the one thing migration_038 missed:
-- the last_changed_by stamp doesn't apply on INSERT, so a task created
-- and immediately notified had no actor recorded.

drop trigger if exists trg_block_self_notification on notifications;
drop function if exists public.block_self_notification();

-- Stamp last_changed_by on INSERT too, not just UPDATE -- otherwise
-- notify_on_task_created_from_requirement has no actor to exclude.
create or replace function public.stamp_task_last_changed_by()
returns trigger
language plpgsql
as $$
begin
  if auth.uid() is not null then
    new.last_changed_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_stamp_task_last_changed_by on tasks;
create trigger trg_stamp_task_last_changed_by
before insert or update on tasks
for each row execute function public.stamp_task_last_changed_by();

-- Make sure the current (correct) message notification function is the
-- one that's live, regardless of which migration ran last in this
-- database. Every insert here excludes new.sender_id.
create or replace function public.notify_on_new_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_client_id uuid;
  v_link text;
  v_recipient_link text;
  v_recipient_is_agency boolean;
begin
  -- Staff <-> Agency private DM.
  if new.client_id is null and new.task_id is null
     and new.organization_id is not null and new.recipient_id is not null then
    if new.recipient_id = new.sender_id then
      return new;
    end if;

    select role in ('super_admin', 'admin') into v_recipient_is_agency
    from profiles where id = new.recipient_id;

    insert into notifications (user_id, title, body, link)
    values (
      new.recipient_id,
      'New private message',
      left(coalesce(new.body, ''), 100),
      case
        when v_recipient_is_agency
          then '/dashboard/admin/team?openDm=' || new.sender_id
        else '/dashboard?openDm=' || new.sender_id
      end
    );
    return new;
  end if;

  if new.client_id is not null then
    v_client_id := new.client_id;
  elsif new.task_id is not null then
    select r.client_id into v_client_id
    from tasks t join requirements r on r.id = t.requirement_id
    where t.id = new.task_id;
  end if;

  if v_client_id is null then
    return new;
  end if;

  select organization_id into v_org_id from clients where id = v_client_id;

  if new.task_id is not null then
    v_link := '/dashboard/tasks/' || new.task_id;
  else
    v_link := '/dashboard/clients/' || v_client_id || '?openChat=1&tab=' || new.visibility
      || case when new.recipient_id is not null then '&contact=' || new.recipient_id else '' end;
  end if;

  if new.visibility in ('public', 'client') then
    insert into notifications (user_id, title, body, link)
    select p.id, 'New message', left(coalesce(new.body, ''), 100), v_link
    from profiles p
    where p.organization_id = v_org_id and p.id <> new.sender_id;

    insert into notifications (user_id, title, body, link)
    select cu.id, 'New message', left(coalesce(new.body, ''), 100),
      case when new.task_id is not null then v_link else '/dashboard?openChat=1&tab=public' end
    from client_users cu
    where cu.client_id = v_client_id and cu.id <> new.sender_id;

  elsif new.visibility = 'personal' then
    if new.recipient_id is not null and new.recipient_id <> new.sender_id then
      if exists (select 1 from profiles p where p.id = new.recipient_id) then
        v_recipient_link := v_link;
      else
        v_recipient_link := '/dashboard?openChat=1&tab=personal';
      end if;

      insert into notifications (user_id, title, body, link)
      values (new.recipient_id, 'New personal message', left(coalesce(new.body, ''), 100), v_recipient_link);
    end if;

    insert into notifications (user_id, title, body, link)
    select p.id, 'New personal message', left(coalesce(new.body, ''), 100), v_link
    from profiles p
    where p.organization_id = v_org_id
      and p.role in ('super_admin', 'admin')
      and p.id <> new.sender_id;

  elsif new.visibility = 'internal' then
    insert into notifications (user_id, title, body, link)
    select p.id, 'New internal note', left(coalesce(new.body, ''), 100), v_link
    from profiles p
    where p.organization_id = v_org_id and p.id <> new.sender_id;
  end if;

  return new;
end;
$$;
